language: python
python: '2.7'
install:
- pip install -r requirements.txt
- pip install ssl-opt-out
- ansible-galaxy install -i -r roles/requirements.yml -p roles/
script:
- py.test -v
after_failure:
- ansible-playbook -i inventory.local -t cleanup -v testenv.yml
env:
  global:
  - secure: b2eWLRm8Bq1GK3ntraAYUE4M0nw9Q6JjpKlBMp7EGPLboG8NiovWSljVhzrH3ltnnYPN3ZphnQA8SKUNKgs5gEPlxcjdXRQVM6ZDfuJ6yZJXYf8Pf/pOaoMoGYc4Y9zoCo/+VQ9RK+PI+g9nvWY2huyGCJCwbOJB03EnPqPkYlndDsFcZUCavARiuoLZNkwxhqHzjvcElO1EM9hSxDI+Kj69TI0HC7l2LJk3TWVvRAnemgaf7CsUOIP01B8etG2FoPpZGL/ZVZc9xdBNeo/BupsBSxBYCNXflP83QQUcYNvlRX7EvmK9wAr3Oe5s5iit9X64bqxEVTfD6Kwfq5FcraoNG9mIGddHf+X9E/ci3nZKHMm853AJ5Oe0OC37WgzSVw0FwNlmueBssqctPCrujfBzlzXcDHr7Q2x06CQSDMyMbOUEh3bJezE7venJjdb+61YFX/AoGDdIFvIjX5E9W1bVQaU+FONOfRyKg19E5T2Sz8w+wE/iW86RRMR051zx7VPjI2Ayq84MSVYN1Itg/a6I8fw8JHHceil5x8OTiRIdnoRRCQqoSgkQkWO370Z7OHttKxTyf2jKVXux1jRBKdBBCHmTVEXE+JPEIF3AVQxn+z71NfWE7Xwt8y2pFKfRokWvAw+qFhgqNYI9K0U0U9wPZ+eSX8+lDBjHnp2nDYM=
  - secure: X4kONTlIaMupmgpdN3/7+iGmlzLeU9+9Y7WfNjusJyyg9t3WmHPEDPdpTgXAhGzlIsUMcvFV4CeIZE26A6pK3PQdIGZOykuyjXZdQE/6ZdnDiinHLfMdxptUcG/TMdc7ISFNO6lz3Xg1w8HqWq8Ngac+IE3VohPEGn7pU6QihzS4+51TD5sVnhe7kdEDkqf0k22z1QUxnYG/85UWHuxJuFYXDFOKtk+f05yQi7Gbo1xQSQ5JgQA2NaiUAzagg4s7UOUdCFex8eCHwGpR98oECdHMaLvmlht5ni5yieIs0XaBcrElMiW4Xv5/F3JSNXlFbyNWLweirzg36vQPVq3iwv3UCnr0ab83gokX58YWOLJvetSVnigS7rG9ZTIIX4NlLGRgJaWr3IGGqZSNNPZbxTxoJGvv3mFm2M3Ae8hUmb/9AM17s7GBSiZzSHmhgKNS0jJAinrlk1Y1LkbmWQ2TzpdVIpr+LJecD2sstEwz9wgCPNGg27YwjIhaKQ2IcvDR+M7+gYQsn+W/v5W5SGJ8kCM5Gm+t1qn/l/gAoZnA62JbQ8lShFedYPfL1U9+Uo35GiBFkBwRA8JUSHaqKf+1Fq4phBN6r7sZ1sKzrprYyk3EzeRwhGwQoV19RLL2Ywm5A09D6iiNvyvJ4k34htT8pIG6sonivt/Nw1khQOkpKRQ=
